HW02 is completed
tabularasa31/otus_hw pull request #2
Opened 2022-06-21 19:40 UTC by tabularasa31

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-06-22 07:35 UTC, egakupi commented on hw02_unpack_string/unpack.go
> +		case string(r[i]) == "\\": // Если обратный слеш
Можно сравнивать `r[i] == '\\'`. Тут и в остальных местах.

2022-06-22 07:39 UTC, egakupi requested changes
Привет! Спасибо за выполненное домашнее задание. Здорово, что получилось сделать дополнительное задание и дополнить положительные тесты. Предлагаю еще добавить немного кейсов в отрицательные тесты.

2022-06-22 16:06 UTC, tabularasa31 commented
> Привет! Спасибо за выполненное домашнее задание. Здорово, что получилось сделать дополнительное задание и дополнить положительные тесты. Предлагаю еще добавить немного кейсов в отрицательные тесты.

Done

2022-06-22 16:07 UTC, tabularasa31 commented on hw02_unpack_string/unpack.go
> +		case string(r[i]) == "\\": // Если обратный слеш
Done^
Thnx!

2022-06-23 07:14 UTC, egakupi commented on hw02_unpack_string/unpack.go
> +			} else if !unicode.IsDigit(r[i-1]) || unicode.IsDigit(r[i-1]) && string(r[i-2]) == "\\" {
Тут еще осталось приведение к строке

2022-06-23 07:41 UTC, tabularasa31 commented on hw02_unpack_string/unpack.go
> +			} else if !unicode.IsDigit(r[i-1]) || unicode.IsDigit(r[i-1]) && string(r[i-2]) == "\\" {
Fixed

2022-06-30 08:04 UTC, egakupi approved these changes
Отлично!

Принято – 10/10

Успехов дальше!

2022-06-30 10:48 UTC, merged